version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: fastapi-web
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    ports:
      - '6000:27017'
