version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: shop-api
    container_name: fastapi-web
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: uvicorn src.main:app --host 0.0.0.0 --reload

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '6000:27017'
