[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.mypy]
exclude = ["tests", ".tests"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["src"]
omit = ["tests/**", "**/__init__.py", "src/config.py"]
