[tool.mypy]
exclude = ["tests", ".tests"]

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true
ignore_missing_imports = true

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["src"]
omit = ["tests/**", "**/__init__.py", "src/config.py"]