apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Values.appName }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-mongodb-service
spec:
  selector:
    app: {{ .Values.appName }}-mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodbPort }}
      targetPort: {{ .Values.mongodbPort }}
      nodePort: {{ .Values.mongoNodePort }}
  type: {{ .Values.mongoServiceType }}
