apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceLabel }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.serviceLabel }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-mongodb-service
spec:
  selector:
    app: {{ .Values.appName }}-mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongoServicePort }}
      targetPort: {{ .Values.mongodbPort }}
  type: {{ .Values.mongoServiceType }}
