name: Run Tests

on: push

env:
  MONGO_USERNAME: fastapi
  MONGO_PASSWORD: pass123
  MONGO_DATABASE: fastapi
  MONGO_PORT: 27017
  MONGO_HOST: mongo
  MONGODB_URL: 'mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: Run Tests
        run: |
          coverage run -m pytest -rf
          flake8
